export const GET_TODOS = "GET_TODOS"
export const ADD_TODO = "ADD_TODO"
export const ARCHIVE_TODO = "ARCHIVE_TODO"
export const MARK_COMPLETED = "MARK_COMPLETED"
export const SAVE_TODOS = "SAVE_TODOS"